id: P006822
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:24:56.333420
source_metadata:
  id: bdr:W15960
  title: དབྱངས་ཅན་གྲུབ་པའི་རྡོ་རྗེའི་རྣམ་ཐར།
  author: ''
  volumes:
    3c44c90a3022495ead5499eb617c3711:
      image_group_id: I6459
      title: ''
      volume_number: 1
      total_pages: 420
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
