id: IC22C0A38
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T11:48:53+00:00'
last_modified: '2022-06-08T07:41:38.922514+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W15960
  title: དབྱངས་ཅན་གྲུབ་པའི་རྡོ་རྗེའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B308:
      image_group_id: I6459
      title: ''
      total_pages: 420
      order: 1
      base_file: B308.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
